//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutualBenefitsFunds.mutualbenefitsfunndsrefrence {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Client", Namespace="http://schemas.datacontract.org/2004/07/MutualBenefitsFundsWcf")]
    [System.SerializableAttribute()]
    public partial class Client : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CmpremiumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdnumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumdepandtsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhonenumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RaddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TittleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cmpremium {
            get {
                return this.CmpremiumField;
            }
            set {
                if ((this.CmpremiumField.Equals(value) != true)) {
                    this.CmpremiumField = value;
                    this.RaisePropertyChanged("Cmpremium");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Idnumber {
            get {
                return this.IdnumberField;
            }
            set {
                if ((object.ReferenceEquals(this.IdnumberField, value) != true)) {
                    this.IdnumberField = value;
                    this.RaisePropertyChanged("Idnumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numdepandts {
            get {
                return this.NumdepandtsField;
            }
            set {
                if ((this.NumdepandtsField.Equals(value) != true)) {
                    this.NumdepandtsField = value;
                    this.RaisePropertyChanged("Numdepandts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Paddress {
            get {
                return this.PaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.PaddressField, value) != true)) {
                    this.PaddressField = value;
                    this.RaisePropertyChanged("Paddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Phonenumber {
            get {
                return this.PhonenumberField;
            }
            set {
                if ((this.PhonenumberField.Equals(value) != true)) {
                    this.PhonenumberField = value;
                    this.RaisePropertyChanged("Phonenumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Raddress {
            get {
                return this.RaddressField;
            }
            set {
                if ((object.ReferenceEquals(this.RaddressField, value) != true)) {
                    this.RaddressField = value;
                    this.RaisePropertyChanged("Raddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tittle {
            get {
                return this.TittleField;
            }
            set {
                if ((object.ReferenceEquals(this.TittleField, value) != true)) {
                    this.TittleField = value;
                    this.RaisePropertyChanged("Tittle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Code", Namespace="http://schemas.datacontract.org/2004/07/MutualBenefitsFundsWcf")]
    [System.SerializableAttribute()]
    public partial class Code : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string C_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cd_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Cd_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cd_incvalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cd_regidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cd_statusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_code {
            get {
                return this.C_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.C_codeField, value) != true)) {
                    this.C_codeField = value;
                    this.RaisePropertyChanged("C_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string C_id {
            get {
                return this.C_idField;
            }
            set {
                if ((object.ReferenceEquals(this.C_idField, value) != true)) {
                    this.C_idField = value;
                    this.RaisePropertyChanged("C_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cd_code {
            get {
                return this.Cd_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.Cd_codeField, value) != true)) {
                    this.Cd_codeField = value;
                    this.RaisePropertyChanged("Cd_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cd_id {
            get {
                return this.Cd_idField;
            }
            set {
                if ((this.Cd_idField.Equals(value) != true)) {
                    this.Cd_idField = value;
                    this.RaisePropertyChanged("Cd_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cd_incval {
            get {
                return this.Cd_incvalField;
            }
            set {
                if ((object.ReferenceEquals(this.Cd_incvalField, value) != true)) {
                    this.Cd_incvalField = value;
                    this.RaisePropertyChanged("Cd_incval");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cd_regid {
            get {
                return this.Cd_regidField;
            }
            set {
                if ((object.ReferenceEquals(this.Cd_regidField, value) != true)) {
                    this.Cd_regidField = value;
                    this.RaisePropertyChanged("Cd_regid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cd_status {
            get {
                return this.Cd_statusField;
            }
            set {
                if ((object.ReferenceEquals(this.Cd_statusField, value) != true)) {
                    this.Cd_statusField = value;
                    this.RaisePropertyChanged("Cd_status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="mutualbenefitsfunndsrefrence.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCLient", ReplyAction="http://tempuri.org/IService1/AddCLientResponse")]
        string AddCLient(string code, string name, string surname, string tittle, string idnumber, int phonenumber, string postAddress, string ResAddress, int cmdaidpremium, int numdependants, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddCLient", ReplyAction="http://tempuri.org/IService1/AddCLientResponse")]
        System.Threading.Tasks.Task<string> AddCLientAsync(string code, string name, string surname, string tittle, string idnumber, int phonenumber, string postAddress, string ResAddress, int cmdaidpremium, int numdependants, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signin", ReplyAction="http://tempuri.org/IService1/signinResponse")]
        string signin(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/signin", ReplyAction="http://tempuri.org/IService1/signinResponse")]
        System.Threading.Tasks.Task<string> signinAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckCode", ReplyAction="http://tempuri.org/IService1/CheckCodeResponse")]
        string CheckCode(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckCode", ReplyAction="http://tempuri.org/IService1/CheckCodeResponse")]
        System.Threading.Tasks.Task<string> CheckCodeAsync(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getID", ReplyAction="http://tempuri.org/IService1/getIDResponse")]
        string getID(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getID", ReplyAction="http://tempuri.org/IService1/getIDResponse")]
        System.Threading.Tasks.Task<string> getIDAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClient", ReplyAction="http://tempuri.org/IService1/GetClientResponse")]
        MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client GetClient(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClient", ReplyAction="http://tempuri.org/IService1/GetClientResponse")]
        System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client> GetClientAsync(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientCode", ReplyAction="http://tempuri.org/IService1/GetClientCodeResponse")]
        MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Code[] GetClientCode(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClientCode", ReplyAction="http://tempuri.org/IService1/GetClientCodeResponse")]
        System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Code[]> GetClientCodeAsync(string cid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIdname", ReplyAction="http://tempuri.org/IService1/GetIdnameResponse")]
        MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client GetIdname(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetIdname", ReplyAction="http://tempuri.org/IService1/GetIdnameResponse")]
        System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client> GetIdnameAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetPassword", ReplyAction="http://tempuri.org/IService1/SetPasswordResponse")]
        string SetPassword(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetPassword", ReplyAction="http://tempuri.org/IService1/SetPasswordResponse")]
        System.Threading.Tasks.Task<string> SetPasswordAsync(string id, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProfile", ReplyAction="http://tempuri.org/IService1/UpdateProfileResponse")]
        string UpdateProfile(string c_id, string Name, string Surname, string Tittle, string idnumber, int phonenumber, string paddress, string raddress, int cmnpremium, int numdepn, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateProfile", ReplyAction="http://tempuri.org/IService1/UpdateProfileResponse")]
        System.Threading.Tasks.Task<string> UpdateProfileAsync(string c_id, string Name, string Surname, string Tittle, string idnumber, int phonenumber, string paddress, string raddress, int cmnpremium, int numdepn, string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MutualBenefitsFunds.mutualbenefitsfunndsrefrence.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.IService1>, MutualBenefitsFunds.mutualbenefitsfunndsrefrence.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddCLient(string code, string name, string surname, string tittle, string idnumber, int phonenumber, string postAddress, string ResAddress, int cmdaidpremium, int numdependants, string email, string password) {
            return base.Channel.AddCLient(code, name, surname, tittle, idnumber, phonenumber, postAddress, ResAddress, cmdaidpremium, numdependants, email, password);
        }
        
        public System.Threading.Tasks.Task<string> AddCLientAsync(string code, string name, string surname, string tittle, string idnumber, int phonenumber, string postAddress, string ResAddress, int cmdaidpremium, int numdependants, string email, string password) {
            return base.Channel.AddCLientAsync(code, name, surname, tittle, idnumber, phonenumber, postAddress, ResAddress, cmdaidpremium, numdependants, email, password);
        }
        
        public string signin(string email, string password) {
            return base.Channel.signin(email, password);
        }
        
        public System.Threading.Tasks.Task<string> signinAsync(string email, string password) {
            return base.Channel.signinAsync(email, password);
        }
        
        public string CheckCode(string code) {
            return base.Channel.CheckCode(code);
        }
        
        public System.Threading.Tasks.Task<string> CheckCodeAsync(string code) {
            return base.Channel.CheckCodeAsync(code);
        }
        
        public string getID(string email, string password) {
            return base.Channel.getID(email, password);
        }
        
        public System.Threading.Tasks.Task<string> getIDAsync(string email, string password) {
            return base.Channel.getIDAsync(email, password);
        }
        
        public MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client GetClient(string cid) {
            return base.Channel.GetClient(cid);
        }
        
        public System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client> GetClientAsync(string cid) {
            return base.Channel.GetClientAsync(cid);
        }
        
        public MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Code[] GetClientCode(string cid) {
            return base.Channel.GetClientCode(cid);
        }
        
        public System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Code[]> GetClientCodeAsync(string cid) {
            return base.Channel.GetClientCodeAsync(cid);
        }
        
        public MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client GetIdname(string email) {
            return base.Channel.GetIdname(email);
        }
        
        public System.Threading.Tasks.Task<MutualBenefitsFunds.mutualbenefitsfunndsrefrence.Client> GetIdnameAsync(string email) {
            return base.Channel.GetIdnameAsync(email);
        }
        
        public string SetPassword(string id, string password) {
            return base.Channel.SetPassword(id, password);
        }
        
        public System.Threading.Tasks.Task<string> SetPasswordAsync(string id, string password) {
            return base.Channel.SetPasswordAsync(id, password);
        }
        
        public string UpdateProfile(string c_id, string Name, string Surname, string Tittle, string idnumber, int phonenumber, string paddress, string raddress, int cmnpremium, int numdepn, string email) {
            return base.Channel.UpdateProfile(c_id, Name, Surname, Tittle, idnumber, phonenumber, paddress, raddress, cmnpremium, numdepn, email);
        }
        
        public System.Threading.Tasks.Task<string> UpdateProfileAsync(string c_id, string Name, string Surname, string Tittle, string idnumber, int phonenumber, string paddress, string raddress, int cmnpremium, int numdepn, string email) {
            return base.Channel.UpdateProfileAsync(c_id, Name, Surname, Tittle, idnumber, phonenumber, paddress, raddress, cmnpremium, numdepn, email);
        }
    }
}
